// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Category struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Post struct {
	ID        int32     `json:"id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UserID    int32     `json:"user_id"`
	ThreadID  int32     `json:"thread_id"`
}

type Thread struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Views     int32     `json:"views"`
	CreatedAt time.Time `json:"created_at"`
	UserID    int32     `json:"user_id"`
}

type ThreadsCategory struct {
	CategoryID int32 `json:"category_id"`
	ThreadID   int32 `json:"thread_id"`
}

type User struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Picture   string    `json:"picture"`
	Sub       string    `json:"sub"`
	CreatedAt time.Time `json:"created_at"`
}
