// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Category struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Post struct {
	ID        int32        `json:"id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	UserID    int32        `json:"user_id"`
	ThreadID  int32        `json:"thread_id"`
}

type Thread struct {
	ID        int32         `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	Views     sql.NullInt32 `json:"views"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	UserID    int32         `json:"user_id"`
}

type ThreadsCategory struct {
	CategoryID int32 `json:"category_id"`
	ThreadID   int32 `json:"thread_id"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Picture   sql.NullString `json:"picture"`
	Sub       string         `json:"sub"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
