// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: thread_category.sql

package db

import (
	"context"
)

const linkThreadAndCategory = `-- name: LinkThreadAndCategory :one
INSERT INTO threads_categories (
    category_id,
    thread_id
) VALUES (
    $1, $2
)
RETURNING category_id, thread_id
`

type LinkThreadAndCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	ThreadID   int32 `json:"thread_id"`
}

func (q *Queries) LinkThreadAndCategory(ctx context.Context, arg LinkThreadAndCategoryParams) (ThreadsCategory, error) {
	row := q.db.QueryRowContext(ctx, linkThreadAndCategory, arg.CategoryID, arg.ThreadID)
	var i ThreadsCategory
	err := row.Scan(&i.CategoryID, &i.ThreadID)
	return i, err
}
